terraform import module.s3.aws_s3_bucket_versioning.disaadev disaadev
terraform import module.s3.aws_s3_bucket_website_configuration.disaadev disaadev
terraform import module.s3.aws_s3_bucket.disaadev disaadev
terraform import module.s3.aws_s3_bucket_server_side_encryption_configuration.disaadev disaadev
terraform import module.s3.aws_s3_bucket_request_payment_configuration.disaadev disaadev
terraform import module.s3.aws_s3_bucket_policy.disaadev disaadev
terraform import module.s3.aws_s3_bucket_ownership_controls.disaadev disaadev
terraform import module.s3.aws_s3_bucket_public_access_block.disaadev disaadev
terraform import module.s3.aws_s3_bucket_acl.disaadev disaadev
terraform import module.lambda.aws_lambda_permission.getVisitors-AllowExecutionFromAPIGateway getVisitors/AllowExecutionFromAPIGateway
terraform import module.lambda.aws_lambda_permission.updateVisitors-AllowExecutionFromAPIGateway updateVisitors/AllowExecutionFromAPIGateway
terraform import module.lambda.aws_lambda_function.getVisitors getVisitors
terraform import module.lambda.aws_lambda_function.updateVisitors updateVisitors
terraform import module.dynamodb.aws_dynamodb_table.resume resume
terraform import module.cloudfront.aws_cloudfront_distribution.E2ZRFDB082WSN6 E2ZRFDB082WSN6
terraform import module.cloudfront.aws_cloudfront_cache_policy.CachingOptimized 658327ea-f89d-4fab-a63d-7e88639e58f6
terraform import module.api_gateway.aws_api_gateway_usage_plan.default-plan coblgm
terraform import module.api_gateway.aws_api_gateway_stage.test-stage 4su6xysix1/test
terraform import module.api_gateway.aws_api_gateway_rest_api.api-4su6xysix1_resumeapi 4su6xysix1
terraform import module.api_gateway.aws_api_gateway_resource.res-21dp4a 4su6xysix1/21dp4a
terraform import module.api_gateway.aws_api_gateway_resource.res-aocwif 4su6xysix1/aocwif
terraform import module.api_gateway.aws_api_gateway_resource.res-ld78n10odb 4su6xysix1/ld78n10odb
terraform import module.api_gateway.aws_api_gateway_model.mod-4t2lu3 4su6xysix1/Empty
terraform import module.api_gateway.aws_api_gateway_model.mod-dpwoid 4su6xysix1/Error
terraform import module.api_gateway.aws_api_gateway_method.met-4su6xysix1-002F-21dp4a-002F-OPTIONS 4su6xysix1/21dp4a/OPTIONS
terraform import module.api_gateway.aws_api_gateway_method.met-4su6xysix1-002F-21dp4a-002F-POST 4su6xysix1/21dp4a/POST
terraform import module.api_gateway.aws_api_gateway_method.met-4su6xysix1-002F-aocwif-002F-GET 4su6xysix1/aocwif/GET
terraform import module.api_gateway.aws_api_gateway_method.met-4su6xysix1-002F-aocwif-002F-OPTIONS 4su6xysix1/aocwif/OPTIONS
terraform import module.api_gateway.aws_api_gateway_method_response.met-4su6xysix1-002F-21dp4a-002F-OPTIONS-002F-200 4su6xysix1/21dp4a/OPTIONS/200
terraform import module.api_gateway.aws_api_gateway_method_response.met-4su6xysix1-002F-21dp4a-002F-POST-002F-200 4su6xysix1/21dp4a/POST/200
terraform import module.api_gateway.aws_api_gateway_method_response.met-4su6xysix1-002F-aocwif-002F-GET-002F-200 4su6xysix1/aocwif/GET/200
terraform import module.api_gateway.aws_api_gateway_method_response.met-3su6xysix1-002F-aocwif-002F-OPTIONS-002F-200 4su6xysix1/aocwif/OPTIONS/200
terraform import module.api_gateway.aws_api_gateway_integration.met-4su6xysix1-002F-21dp4a-002F-OPTIONS 4su6xysix1/21dp4a/OPTIONS
terraform import module.api_gateway.aws_api_gateway_integration.met-4su6xysix1-002F-21dp4a-002F-POST 4su6xysix1/21dp4a/POST
terraform import module.api_gateway.aws_api_gateway_integration.met-4su6xysix1-002F-aocwif-002F-OPTIONS 4su6xysix1/aocwif/OPTIONS
terraform import module.api_gateway.aws_api_gateway_integration.met-4su6xysix1-002F-aocwif-002F-GET 4su6xysix1/aocwif/GET
terraform import module.api_gateway.aws_api_gateway_integration_response.met-4su6xysix1-002F-21dp4a-002F-OPTIONS-002F-200 4su6xysix1/21dp4a/OPTIONS/200
terraform import module.api_gateway.aws_api_gateway_integration_response.met-4su6xysix1-002F-21dp4a-002F-POST-002F-200 4su6xysix1/21dp4a/POST/200
terraform import module.api_gateway.aws_api_gateway_integration_response.met-4su6xysix1-002F-aocwif-002F-OPTIONS-002F-200 4su6xysix1/aocwif/OPTIONS/200
terraform import module.api_gateway.aws_api_gateway_integration_response.met-4su6xysix1-002F-aocwif-002F-GET-002F-200 4su6xysix1/aocwif/GET/200
terraform import module.api_gateway.aws_api_gateway_gateway_response.res-4su6xysix1-002F-DEFAULT_4XX 4su6xysix1/DEFAULT_4XX
