name: "Terraform"

on:
  workflow_run:
    workflows: ["lambda testing"]
    types:
      - completed
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        # Use the AWS GitHub Action to configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::767398113748:role/web-resume-back

      # Setup Terraform using the official Terraform GitHub Action
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Initialize a new or existing Terraform working directory
      - name: Terraform Init
        run: terraform init

      # Check that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Generate an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false

      # Apply Terraform configuration if the workflow run event is a push
      - name: Terraform Apply
        if: ${{ github.event.workflow_run.event == 'push' }}
        run: terraform apply -auto-approve -input=false
